@TechStore.Api_HostAddress = http://localhost:5175

GET {{TechStore.Api_HostAddress}}/api/products
Accept: application/json

###

POST {{TechStore.Api_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Notebook",
  "description": "Modelo de exemplo",
  "price": 3499.90,
  "stockQuantity": 5
}

###

PUT {{TechStore.Api_HostAddress}}/api/products/1
Content-Type: application/json

{
  "name": "Notebook atualizado",
  "description": "Modelo de exemplo",
  "price": 3299.90,
  "stockQuantity": 4
}

###

DELETE {{TechStore.Api_HostAddress}}/api/products/1

###
